// Ambient type declarations for icechunk-js.
//
// icechunk-js is currently pinned to a GitHub commit tarball. GitHub archives
// contain only git-tracked source files, so the compiled dist/ output
// (generated by the package's prepare script) is absent unless pnpm runs the
// build step. These declarations mirror the exact API surface used in
// load-zarr.ts so TypeScript can resolve the module regardless.
//
// Remove this file once icechunk-js ships pre-built declarations in the
// tarball or is back on an npm release.

declare module "icechunk-js" {
  export enum SpecVersion {
    V1_0 = 0,
    V2_0 = 1,
  }

  export class HttpStorage {
    constructor(url: string);
  }

  export interface Session {
    getSpecVersion(): SpecVersion;
    getSnapshotId(): Uint8Array;
    getMessage(): string;
    getFlushedAt(): Date;
  }

  export interface NodeInfo {
    path: string;
    nodeData: { type: string };
  }

  export class IcechunkStore {
    static open(
      session: Session,
      options?: { withRangeCoalescing?: unknown },
    ): Promise<IcechunkStore>;
    listNodes(): NodeInfo[];
    get(
      key: string,
      opts?: { signal?: AbortSignal },
    ): Promise<Uint8Array | undefined>;
    getRange?: (
      key: string,
      range: [number | null, number | null],
      opts?: { signal?: AbortSignal },
    ) => Promise<Uint8Array | undefined>;
  }

  export class Repository {
    static open(options: { storage: HttpStorage }): Promise<Repository>;
    listBranches(): Promise<string[]>;
    listTags(): Promise<string[]>;
    checkoutBranch(branch: string): Promise<Session>;
  }

  export function encodeObjectId12(id: Uint8Array): string;
}
